import trip1Main from "/public/assets/trips/101.jpg";
import trip1_2 from "/public/assets/trips/102.jpg";
import trip1_4 from "/public/assets/trips/104.jpg";
import trip1_5 from "/public/assets/trips/105.jpg";
import trip1_6 from "/public/assets/trips/106.jpg";
import trip1_7 from "/public/assets/trips/107.jpg";
import trip2_Main from "/public/assets/trips/200.jpg";
import trip2_1 from "/public/assets/trips/201.png";
import trip2_2 from "/public/assets/trips/202.png";
import trip2_3 from "/public/assets/trips/203.png";
import trip2_4 from "/public/assets/trips/204.png";
import trip2_5 from "/public/assets/trips/205.png";
import trip3_Main from "/public/assets/trips/301.jpg";
import trip3_2 from "/public/assets/trips/302.jpg";
import trip3_3 from "/public/assets/trips/303.jpg";
import trip3_4 from "/public/assets/trips/304.jpg";
import trip3_5 from "/public/assets/trips/305.jpg";
import trip3_6 from "/public/assets/trips/306.jpg";
import trip3_7 from "/public/assets/trips/307.jpg";
import trip4_Main from "/public/assets/trips/401.jpg";
import trip4_2 from "/public/assets/trips/402.jpg";
import trip4_3 from "/public/assets/trips/403.jpg";
import trip4_4 from "/public/assets/trips/404.jpg";
import trip4_5 from "/public/assets/trips/405.jpg";
import trip4_6 from "/public/assets/trips/406.jpg";
import trip4_7 from "/public/assets/trips/407.jpg";
import trip4_8 from "/public/assets/trips/408.jpg";
import trip5_Main from "/public/assets/trips/501.jpg";
import trip5_2 from "/public/assets/trips/502.jpg";
import trip5_3 from "/public/assets/trips/503.jpg";
import trip5_4 from "/public/assets/trips/504.jpg";
import trip6_Main from "/public/assets/trips/601.jpg";
import trip6_2 from "/public/assets/trips/602.jpg";
import trip6_3 from "/public/assets/trips/603.jpg";
import trip6_4 from "/public/assets/trips/604.jpg";
import trip7_main from "/public/assets/trips/701.jpg";
import trip7_2 from "/public/assets/trips/702.jpg";
import trip7_3 from "/public/assets/trips/703.jpg";
import trip7_4 from "/public/assets/trips/704.jpg";
import trip8_Main from "/public/assets/trips/801.jpg";
import trip8_2 from "/public/assets/trips/802.jpg";
import trip8_3 from "/public/assets/trips/803.jpg";
import trip8_4 from "/public/assets/trips/804.jpg";
import trip8_5 from "/public/assets/trips/805.jpg";
import trip8_6 from "/public/assets/trips/806.jpg";
import trip8_7 from "/public/assets/trips/807.jpg";
import trip8_8 from "/public/assets/trips/808.jpg";
import trip9_Main from "/public/assets/trips/901.jpg";
import trip9_2 from "/public/assets/trips/902.jpg";
import trip9_4 from "/public/assets/trips/904.jpg";
import trip9_5 from "/public/assets/trips/905.jpg";
import trip9_6 from "/public/assets/trips/906.jpg";
import trip9_7 from "/public/assets/trips/907.jpg";
import trip10_Main from "/public/assets/trips/1001.jpg";
import trip10_2 from "/public/assets/trips/1002.jpg";
import trip10_3 from "/public/assets/trips/1003.jpg";
import trip10_4 from "/public/assets/trips/1004.jpg";
import trip10_5 from "/public/assets/trips/1005.jpg";

export const tripsGr = [
  {
    id: "trip1",
    name: "Angel und Pferdereittour zu den Hagiin Har See",
    mainImg: trip1Main,
    desc: "Eine der sehenswerten Attraktionen, die Touristen anzieht, ist der berühmte Hagiin Har nuur in der Khan Khenti-Bergkette, einem unantastbaren Naturschutzgebiet. Um den Ort zu erreichen, reisen Sie zu Pferd durch die wilde Wildnis und erleben die Schönheit der Natur hautnah, vorbei an wunderschönen Bergen, Flüssen und Wäldern. ",
    desc2:
      "Es ist auch eine Reise, die etwas Besonderes ist, als nur zu einem Ort zu fahren, an dem Sie Wildtiere beobachten können. Ein Paradies, in dem Sie jeden Tag an einer neuen Stelle angeln können. ",
    nights: "10 Nächte",
    days: "10 Tage",
    meeting: "20.06.2023, 25.07.2023, 15.08.2023, 10.09.2023",
    group: "2-12",
    price: "2200$ - 1400$",
    hotel: "Zelte, Hotel",
    transport: "Mini van, Mongolische Pferde",
    paragraph: [
      "1 Tag: Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen -Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2 Tag: Nach dem Früstuck fängt unsere Reise an. In Terelj wird auf uns unsere Pferde mit Pferdebegleitern warten. Nach der kurzen Bekanntschaft und Einleitung zur Besonderheiten des Mongolischen Pferdes werden wir weiter zur Übernachtungsplatz, am Ufer von Tuul Flusses reiten. (Übernachtung im Zelt)",
      "3 Tag: Nachdem Zelte abgebaut und alles gepackt haben, reiten wir weiter durch die schöne Landschaft zur unseren nächsten Rastplatz. Àb heute werden wir unsere Gepäcke aufs Lastpferde packen. Unterwegs werden wir bei jede schöne Stelle unsere Angelroute werfen um Abendessen zu bereichern. Heute zelten wir Nah an Quelle des Tuul Flußes. (Übernachtung im Zelt)",
      "4 Tag: Reitend durch schöne Landschaf kommen wir an schönen Drei Seen und zelten wir da. (Übernachtung im Zelt) ",
      "5 Tag: Weiter reitend kommen wir an unseren Ziel – See Hagiin Har. Es ist ein malerischer See inmitten im Khentii-Gebirge, zwischen Hiidiin Saridag, Khunkher-Gebirge und Asgat Saridag. Der See ist 2,7 Quadratkilometer lang und 2,5 Kilometer lang und 1,1 Kilometer breit. Die durchschnittliche Tiefe beträgt 11 Meter und die tiefste kann 25 Meter erreichen. Von weiten sieht man die dunkle von Algenwasser davon ist der Name des Sees auf das Auftreten zurückzuführen. (Übernachtung im Zelt)",
      "6 Tag: Freie Tag. Man kann wandern, angeln oder nur relaxen. Am Abend werden wir ein Feurfest veranstalten. (Übernachtung im Zelt)",
      "7 Tag: Heute wir werden durch sagenhafte Felsen und Bergen reitend kommen an Fluß Khongoriin, wo es die hoch Bergigen klarwasser befindliche Äsche zu angeln gibt. (Übernachtung im Zelt)",
      "8 Tag: Wir reitend kommen an die Stelle Har Us von Tuul Flusses, wo wir auch angeln werden. (Übernachtung im Zelt)",
      "9 Tag: Heute reiten wir zurück zu Pferdefamilie. Übergabe des Pferdes. Bekanntschaft mit der Mongolischen Bräuchen und Kultur. Zu Abendessen wird das traditionelle mongolisches Gericht auf einzigartigen Art zubereitet und gegessen. (Übernachtung im Zelt)",
      "10 Tag: Fahrt nach UB. Einkaufsmöglichkeit in nationalen Brands wie cashmer. Besichtigung des Nationales Folklor und danach Abendessen. (Hotel Übernachtung)    ",
      "11 Tag: Abfahrt zu Flughafen. Abflug ",
      "Im Preis enthalten:",
      "2 Nächte im 3-4 sterniges Hotel mit 2 Betten. Wenn man alleine in Zimmer unterkommen wollen, zahlen Sie drauf. ",
      "8 Nächte im Zelt ",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden    ",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip1_2, trip1_4, trip1_5, trip1_6, trip1_7],
  },
  {
    id: "trip2",
    name: "Pferde Reittour zu Hagiin Har nuur ",
    mainImg: trip2_Main,
    desc: "Diese Reise ist ein Ausritt durch das besondere Schutzgebiet des Khan Khenti-Gebirges entlang des Kamms des Khenti-Gebirges. Um den Ort zu erreichen, reisen Sie zu Pferd in die wilde Wildnis, erleben die Schönheit der Natur näher und passieren hohe Berge, Flüsse und Wälder. ",
    desc2:
      "Es ist auch eine Reise, die etwas Besonderes ist, als nur zu einem Ort zu fahren, an dem Sie Wildtiere beobachten können. Die Besonderheit der Reise ist, den Tag an den Ufern von Flüssen und Seen zu verbringen.",
    nights: "11 Nächte",
    days: "12 Tage",
    meeting: "10.06.2023, 01.08.2023, 26.08.2023",
    group: "2-12",
    price: "2500$ - 1300$",
    hotel: "Zelte, Ger camp, Hotel",
    transport: "Mini van, Mongolische Pferde, Kamel",
    paragraph: [
      "1.Tag:  Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen -Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2.Tag: Nach der Frühstuck fahren wir nach Terelj, welche liegt  im Osten ca. 70 km von Ulaanbaatar. Da wird jeder “eigene” Pferde bekommen. Erste Bekannschaft und Einweisungen zu Besonderheiten des Mongolischen Pferdes und reiten wir zu unser Übernachtungsplatz. (Zelt Übernachtung)  ",
      "3.Tag: Nach der Frühstuck bauen wir die Zelte ab, packen wir unser Hab und Gut aufs Pferd und reiten wir entlang des Tuul Flußes. Tuul Fluß fließt auch durch Ulaanbaatar. Unterwegs haben wir Picknick-Mittagessen. Wir reiten weiter hoch entlang des Flusses. (Zelt Übernachtung)",
      "4.Tag: Heute reiten wir durch die schöne Naturschutgebiet Gorhi-Terelj. Picknick-Mittagessen. Übernachtungsplatz ist am Ufer von Fluß Tuul, welche Länge beträgt 819 km. (Zelt Übernachtung)  ",
      "5.Tag: Wir reitend kommen zum See Hagiin Har. Unterwegs haben wir unser Picknick-Mittagessen. Es ist ein malerischer See inmitten im Khentii-Gebirge, zwischen Hiidiin Saridag, Khunkher-Gebirge und Asgat Saridag. Der See ist 2,7 Quadratkilometer lang und 2,5 Kilometer lang und 1,1 Kilometer breit. Die durchschnittliche Tiefe beträgt 11 Meter und die tiefste kann 25 Meter erreichen. Von weiten sieht man die dunkle von Algenwasser davon ist der Name des Sees auf das Auftreten zurückzuführen. (Zelt Übernachtung) ",
      "6.Tag: Freie Tag am Ufer des See Hagiin Har. Man kann wandern, angeln oder eben nur relaxen. Im See gibt es verschiedene Fische wie Äsche, Barsch und Bachforelle. Abends werden wir Feuerfest veranstalten. (Zelt Übernachtung)  ",
      "7.Tag: Heute reiten wir durch Felsen und Bergpässe und  kommen an kleinen Fluß Khongor. Unterwegs haben wir unser Picknick-Mittagessen. (Zelt Übernachtung)  ",
      "8.Tag: Wir reiten duch unberührte Landschaft mit wunderschönen Wiese volle Blumen und kommen zu unser Übernachtungsplatz Huh Had. Unterwegs haben wir unser Picknick-Mittagessen. (Zelt Übernachtung)  ",
      "9.Tag: Am letzten Tag reiten wir zurück zu Pferdebesitzerfamilie. Pferde Übergabe. Besuch und Bekanntschaft mit der Mongolischen Bräuchen und Kultur. Abschiedsabend. (Zelt Übernachtung)  ",
      "10.Tag: Fahrt nach Ulaanbaatar. Unterkommen im Hotel. Einkaufsmöglichkeit von mongolischen berühmten Cashmer. Besuch in Nationales Folklorekonzert und Abendessen. (Hotel Übernachtung)  ",
      "11.Tag: Abfahrt zu Flughafen. Abflug",
      "Im Preis enthalten:",
      "Unterkunft: 2 Nächte im 3-4 sterniges Hotel mit 2 Betten ",
      "8 Nächte im Zelt ",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip2_1, trip2_2, trip2_3, trip2_4, trip2_5],
  },
  {
    id: "trip3",
    name: "Rundreise durch Uvurhangai, Arhangai und Huvsgul aimags",
    mainImg: trip3_Main,
    desc: "Orkhon-Flußtal in Uvurkhangai aimag - Wiege der nomadischen Zivilisation der Mongolei, Arkhangai – Heimat vonVulkane und Touristenorte,",
    desc2:
      "Khuvsgul - der größte und tiefste See der Mongolei. Der Khuvsgul-See ist einer der 17 antiken Seen der Welt. Mongolische unberührte wilde Taiga",
    nights: "11 Nächte",
    days: "12 Tage",
    meeting: "18.06.2023, 13.08.2023, 20.09.2023",
    group: "2-12",
    price: "2800$ - 1400$",
    hotel: "Zelte, Ger camp, Hotel",
    transport: "Mini van, Kamel",
    paragraph: [
      "1.Tag: Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen -Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2.Tag: Nach der Frühstück fängt unsere Reise an. Wir verlassen die Hauptstadt in west - südwestlicher Richtung und betreten Elsen Tasarhai. Es ist eine Provinz in Khangai und trifft auf einen Sandstreifen, der die Mongolei durchquert. Man kann den mongolischen Zweihöckige Kamele reiten. Genießen Sie die einzigartige Aussicht auf die Sanddünen und die einzigartige Flora und Fauna der Wüstenregion. (Übernachtung im mongolischen Ger, Yurte) ",
      "3.Tag: Fahrt weiter nach Süd-West, Uvurhangai aimag. Wir werden die Ruinen der antiken Hauptstadt Khar- Horin, welches im Jahre 1220  durch Chingiskhaan gegruendet wurde, besuchen. Da befindet sich der vom ersten Bogd Zanabazar gegründete alte Kloster Erdene Zuu, welche von den überresten von alten Hauptsatdt gebaut wurde. Weitere Besuche von den mongolischen historischen Komplex und den Froschfelsen usw. Danach fahren wir zu Tuwhunkloster und zelten wir in der Nähe.  (Zelt übernachtung)",
      "4.Tag: Nach der Frühstück gehen wir spazieren zu Tuvkhun-Kloster. Es wurde vom ersten Bogd Zanabazar der Mongolei gegründet. Ein Spaziergang durch die üppigen Wälder und Lärchenwälder des Gebiets des Klosters, das sich auf der Gletscher-Bergwiese befindet. Nachmittags fahren wir in Richtung Westen zu heißquelle Zenkher, welche liegen ca.1600 m hoch über die Meerespiegel. Diese Quelle hat eine Temperatur von 86 Grad über dem Boden, enthält viele natürliche Mineralien und es wurde untersucht, dass sie nützlich ist, um den menschlichen Körper zu entspannen, Müdigkeit zu lindern und allergische Gelenk- und Hauterkrankungen zu behandeln. Übernachtung bei den Quellen von Arkhangai aimag. (Übernachtung im Gercamp) ",
      "5.Tag: Weiterfahrt nach Westen. Wanderung in Naturschutzpark zu erlöschener Vulkankrater Horgo. Unterkunft bei See Terhiin Zagaan. (Übernachtung im Gercamp)",
      "6.Tag: Fahrt nach Norden in Richtung See Huvsgul. Campieren wir nicht weit von Shine Ider. (Zelt übernachtung)",
      "7.Tag: Weiterfahrt nach Norden, Huvsgul aimag. Verbringen Sie die Nacht am Ufer des Khuvsgul-Sees. Der Khuvsgol-See ist der größte und tiefste See der Mongolei und gehört zu der größten Süßwassersee nicht nur der Mongolei, sondern auch der Welt. Der Khuvsgul-See gilt als einer der siebzehn alten Seen auf der Welt. Unterkunft in Hatgal, am Ufer des See. (Übernachtung im Gercamp)",
      "8.Tag: Freie Tag. Man kann wandern, angeln oder nur relaxen. Mittagessen wird eingepackt. An diesem Tag lernen wir das Leben und die Lebensgrundlagen der Familie Tzaatan kennen. Die in der Khuvsgol-Taiga, dem abgelegenen nördlichen Teil der Mongolei, lebenden Tzaatans sind die letzten Rentierzüchter-Stämme auf der Erde. Nur 44 Familien haben ihre traditionelle Lebensweise bewahrt. Der Lebensunterhalt jeder Familie dort hängt nur von einer Sache ab. Durch die Zubereitung von Tee aus RentierMilch und die Verwendung als Reittier für die Nomaden werden sie bei all ihren täglichen Alltag gebraucht.  (Übernachtung im Gercamp)",
      "9.Tag: Fahrt Süd-Ost. Wir verlassen die Provinz Khuvsgul und verbringen die Nacht in der Provinz Bulgan. Unterwegs besuchen wir den erloschenen Vulkan namens Uran-Krater, der ein Merkmal der Provinz Bulgan ist. Er liegt 1686 Meter über dem Meeresspiegel und hat an der Spitze einen 500-600 Meter breiten und 50-60 Meter tiefen Krater. Die Höhe des Togo-Berges beträgt 1620 Meter. Dieser Berg wurde 1965 unter besonderen staatlichen Schutz gestellt. Unterkunft zwischen Ikh Uul und Hutag Undur. (Zelt übernachtung)",
      "10.Tag: Nach ca.180 km Fahrt werden wir bei Bulgan aimak campieren. (Zelt übernachtung)",
      "11.Tag: Fahrt in Richtung Süd, Tuv aimag. Heute besuchen wir den berühmten Hustain Mountain National Park. Seit das Gebiet 1993 unter besonderen Schutz gestellt wurde, um die in der Natur ausgestorbenen Wildpferde (Przewalski-Pferde) wieder anzusiedeln, hat die Zahl der Pferde mehr als 390 erreicht. Hirsche, Seidenäffchen, Antilopen und 213 Vogelarten wurden eingeführt und ihre Zahl nimmt stetig zu. Machen Sie einen Spaziergang durch den Nationalpark und sehen Sie seltene Wildtiere wie das auf der Roten Liste stehende wilde Urpferde Tahi und andere Tiere. (Übernachtung im Gercamp)",
      "12.Tag: Fahrt nach Ulaanbaatar. Nach Mittaessen werden wir shopping bummel durch mongolische Brands wie cashmer usw. Danach nationale Folklore. Abschieds Abendessen. (Hotel Übernachtung)  ",
      "13.Tag: Abfahrt zu Flughafen. Abflug",
      "Im Preis enthalten:",
      "2 Nächte im 3-4 sternigen Hotel, im Zimmer sind zu 2 Personen. Wenn man alleine in Zimmer            unterkommen wollen	, zahlen Sie drauf. ",
      "6 Nächte im Mongolischen Ger ",
      "4 Nächte im Zelt",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip3_2, trip3_3, trip3_4, trip3_5, trip3_6, trip3_7],
  },
  {
    id: "trip4",
    mainImg: trip4_Main,
    name: "Reitttour in Uvurhangai aimag",
    desc: "Das Orkhon-Tal liegt am Ufer des Orkhon-Flusses in der Zentralmongolei. Im Jahre 2004 auf ihren 28. Tagung wurde Orkhon-Tal in die Liste des UNESCO-Weltkulturerbes aufgenommen. ",
    desc2:
      "Das Orkhon River Valley ist seit Jahrhunderten das Zentrum mächtiger Steppennomadenreiche. Dieser wunderschöne Ort mit seiner wunderschönen Natur zieht weiterhin viele in- und ausländische Touristen an. Orkhon-Flußtal in Uvurkhangai aimag - Wiege der nomadischen Zivilisation der Mongolei. Sie werden auf „eigenen“ Pferd Klöster, Heilquelle, Wasserfall, Nomadenfamilien, von Chingis Khaan gegründete erste Hauptstad Khar-Horin erleben und besichtigen.",
    nights: "10 Nächte",
    days: "11 Tage",
    // meeting: '20.06.2023, 25.07.2023, 15.08.2023, 10.09.2023',
    // group: '2-12',
    // price: '2200$ - 1400$',
    // hotel: 'Zelte, Hotel',
    // transport: 'Mini van, Mongolische Pferde',
    paragraph: [
      "1.Tag: Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen -Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2.Tag: Nach der Frühstück fängt unsere Reise an. Wir verlassen die Hauptstadt in südwestlicher Richtung. Unterwegs essen wir Mittagessen. Danach fahren wir weiter ins Orkhon-Tal, die Wiege der nomadischen Zivilisation der Mongolen. Schließlich kommen wir zu unseren Nomadenfamilie an. (Übernachtung im Zelt) ",
      "3.Tag: Nach der Frühstück jede Reiter/in bekommt „eigenes“ Pferd. Erste Bekannschaft, kurze Belehrung zu besonderheiten des mongolischen Pferdes. Kurze Ritte im Umgebung. Dabei werden Sie uralte Begräbnisse (Khirigsur), sowie uralte Steinzeichnungen anschauen. Abends besuch bei Nomaden Familie, Pferdebesitzer. Bekanntschaft mit der Mongolischen Bräuchen und Kultur. (Übernachtung im Zelt)",
      "4.Tag: Am Morgen reiten wir in Richtung Westen. Ritt bei Klippe „Uurtiin tohoi“, Besichtigungen von uralten Beerdigung mit Hirsch steinen. Unterwegs haben wir unser Picknick-Mittagessen. Unser Lager schlagen wir am Ufer des Flusses Orkhon, Hadan hushuu auf. (Übernachtung im Zelt)",
      "5.Tag: Heute reiten wir durch den Tal mit Basalt-Lavagesteine weiter nach Westen, zum größten Wasserfall der Mongolei „Ulaan zutgalan”. Unterwegs haben wir unser Picknick-Mittagessen. Der Wasserfall fließt von 24 m Höhe in die Tiefe und fließt zu Fluß Orkhon. (Übernachtung im Zelt)",
      "6.Tag: Weiterritt nach Westen und kommen wir wie möglich Nah ans Hyatruun Am, wo wir schlagen die Zelte auf. In Hyatruun gibt es warm und kalt Quellen. Sie befindet sich inmitten einer Waldlücke in einer Entfernung von 46 Kilometern von Bat-Ulzii Sum. Außerdem befindet es sich in einem steilen Berg, der nicht mit dem Auto erreicht werden kann, so dass es notwendig ist, fünfzehn Kilometer mit dem Pferd bis zur Spitze anzukommen. Diese warm und kalte Quelle ist nicht nur gut für alle inneren Organe, sondern auch für das Sehvermögen und Allergien, daher kommen Menschen aus nah und fern hierher. Verwenden Sie beim Betreten dieses Natur Spa keine Seife oder Shampoo. Achten Sie darauf, nur umweltfreundliche Seifen zu verwenden. Unterwegs haben wir unser Picknick-Mittagessen. All diese Berge sind ein Teil von großen Bergkette Han Hentii. (Übernachtung im Zelt)",
      "7.Tag: Heute reiten wir zurück vorbei von Wasserfalls und kommen wir an Orkhon Fluß. Unterwegs haben wir unser Picknick-Mittagessen. Unser Lager schlagen wir am Ufer des Flußes Orkhon, nich weit der Brücke Ongoztoin. (Übernachtung im Zelt)",
      "Tag: Weiterritt und Besuch in Kloster “Tuvkhun”. Es ist eines der ältesten buddhistischen Klöster in der Mongolei und befindet sich auf dem Gipfel des Shireet Ulaan-Berges auf 2.600 Metern über dem Meeresspiegel. Der Hochheilige Zanabazar erfand das Soyombo-Buchstaben als er im Tuvkhun-Kloster saß. Unterwegs haben wir unser Picknick-Mittagessen. Danach reiten wir den Fluss entlang in Richtung Har-Horin. (Übernachtung im Zelt)",
      "9.Tag: Nach der Frühstück reiten wir in Richtung Har-Horin Stadt. Unterwegs haben wir unser Picknick-Mittagessen. Campieren wir in Moiltiin Am. Abschied von Pferden und Pferdebegleitern. (Übernachtung im Zelt)",
      "10.Tag: Fahrt nach Khar-Horin, erste Hauptstadt der Mongolen. Besuch in Kloster Erdene Zuu, welche von Überresten von alten Hauptstadt gebaut wurde. Da in Umgebung werden wir andere Sehenswürdigkeiten besichtigen. Unterwegs haben wir unser Picknick-Mittagessen. Danach fahren wir in Richtung Ulaanbaatar. Übernachtung in Elsen Tasarkhai, wo Sie zwei Höckige Kamele reiten können. (Übernachtung im Ger camp)",
      "11.Tag: Fahrt nach Ulaanbaatar. Hotel transfer. Besuch in mongolischen Markenläden wie cashmere. Danach ist nationale Folklore angesagt. Abschiedsabendessen. (Übernachtung im Hotel)",
      "12 Tag: Abfahrt zu Flughafen. Abflug",
      ",Im Preis enthalten:",
      ",2 Nächte im 3-4 sternigen Hotel, im Zimmer sind zu 2 Personen. ",
      ",1 Nächte im Mongolischen Ger     ",
      ",8 Nächte im Zelt",
      ",Führungs- und Dolmetscherservice",
      ",Vollpension Mahlzeiten ",
      ",Getanktes Auto mit dem Fahrer",
      ",Liebevolle zahme Pferde mit russischen Sattel  ",
      ",Freundliche Pferdebegleiter",
      ",Eintrittsgelder für Schutzgebiete und Nationalparks",
      ",Museen und kulturelle Darbietungen",
      ",Campingausrüstung",
      "",
      ",Im Preis nicht enthalten:",
      ",Internationaler Flugpreis",
      ",Übergepäckgebühren",
      ",Reiseversicherung ",
      ",Einzelzimmerzuschlag",
      ",Verschiedene sonder Getränke",
      ",Persönliche Ausrüstung",
      ",Die zusätzlichen Kosten für die Fotografie in Museen usw",
      ",Tipp für einen Reiseleiter, Fahrer usw. ",
      ",Alle zusätzlichen Kosten, die oben nicht erwähnt wurden",
      "",
      ",Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      ",Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip4_2, trip4_3, trip4_4, trip4_5, trip4_6, trip4_7, trip4_8],
  },
  {
    id: "trip5",
    name: "Reitttour in Nationalpark Gorkhi-Terelj ",
    mainImg: trip5_Main,
    desc2:
      "Der Gorkhi-Terelj-Nationalpark ist eine wunderschöne Kombination aus Flüssen, Bergen, Blumen und Bäumen. Da es sich um ein Schutzgebiet handelt, gibt es keine Autos oder Häuser, und Sie können hier die Schönheit der Natur sehen und erleben.",
    nights: "6 Nächte",
    days: "7 Tage",
    meeting: "04.06.2023, 29.06.2023, 27.08.2023 ",
    group: "2-12",
    price: "1500$ - 800$",
    hotel: "Zelte, Hotel",
    transport: "Mini van, Mongolische Pferde",
    paragraph: [
      "1.Tag: Wir holen Sie am Flughafen ab und fahren sofort von der Hauptstadt nach Osten, nach Terelj. Und übernachten wir am Ufer des Tuul Flußes. Von hier aus wird das Auto zurückkehren und der Ausritt wird morgen beginnen. Hier treffen wir unsere Pferde und Pferdebegleiter.  (Zelt Übernachtung)  ",
      "2.Tag: Nach der Frühstück packen wir unsere Sachen auf dem Packpferd und geht es los. Ganzen Tag reiten wir durch den bewaldeten Berg und kommen wir an Fluß, welches fließt zwischen die Berge. Da werden wir auch übernachten. (Übernachtung im Zelt) ",
      "3.Tag: Heute werden wir hier übernachten. Nach dem Frühstück reiten wir zur Gunjiin Sum, was Prinzessinkloster bezeichnet. Unser Mittagessen nehmen wir mit und essen wir es unterwegs. Im wunderschönen Kiefernwald befinden sich die Überreste eines Tempels, der für die Prinzessin der Mandschu-Dynastie erbaut wurde. 1699 kam die Prinzessin der Mandschu-Qing-Dynastie als Königin des mongolischen Dondovdorj nach Khalkha. Als die Prinzessin 1740 starb, sagte sie „da ich heiratete einen Mongolen und somit bin ich bereits eine Mongolin geworden. Nach meinen Tod begrabe mich deshalb auf mongolischem Boden.“ (Übernachtung im Zelt)",
      "4.Tag: Ganzen Tag reiten wir durch wunderschönes Naturschutzgebiet",
      "5.Tag: Heute reite wir zurück zu Pferdefamilie. Übergabe des Pferdes. Bekanntschaft mit der Mongolischen Bräuchen und Kultur. Zu Abendessen wird das traditionelle mongolisches Gericht mit einem einzigartigen Design gegessen. (Übernachtung im Zelt)",
      "6.Tag: Fahrt nach Ulaanbaatar. Hotel transfer. Besichtigen wir Sukhbaatarplatz, Nationale Folklore Konzert, Einkaufsmöglichkeit in mongolischen Markenläden wie cashmir usw. Abendessen. (Übernachtung im Hotel)",
      "7.Tag: Abfahrt zu Flughafen. Abflug",

      "Im Preis enthalten:",
      "1 Nacht im 3-4 sternigen Hotel, im Zimmer fuer 2 Personen. ",
      "5 Nächte im Zelt     ",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden",
      "",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip5_2, trip5_3, trip5_4],
  },
  {
    id: "trip6",
    name: "Reittour zu den Herhluu 3 Seen ",
    mainImg: trip6_Main,
    desc: "Die Reise führt uns in ein unberührter und wunderschöner Ort namens HERHLURIN SARDAG im Naturschutzgebiet Khan Hent. Die Besonderheit der Reise ist, den Tag an den Ufern von Flüssen und Seen zu verbringen. Auch das Baden im Hauptsee nach einer Fahrt in der Hitze des Tages ist ein unermeßliches Glück.",
    // desc2: 'Es ist auch eine Reise, die etwas Besonderes ist, als nur zu einem Ort zu fahren, an dem Sie Wildtiere beobachten können. Die Besonderheit der Reise ist, den Tag an den Ufern von Flüssen und Seen zu verbringen.',
    nights: "10 Nächte",
    days: "11 Tage",
    meeting: "06.06.2023, 18.07.2023, 29.08.2023 ",
    group: "2-12",
    price: "2000$ - 1400$",
    hotel: "Zelte, Hotel",
    transport: "Mini van, Mongolische Pferde",
    paragraph: [
      "1.Tag: Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen-Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2.Tag: Nach der Frühstuck fahren wir nach Terelj, welche liegt  im Osten ca. 70 km von Ulaanbaatar. Da wird jeder “eigene” Pferde bekommen. Erste Bekannschaft und Einweisungen zu Besonderheiten des Mongolischen Pferdes und reiten wir zu unser Übernachtungsplatz. (Zelt Übernachtung)  ",
      "3.Tag: Gefrühstückt bauen wir die Zelte ab, packen wir unser Hab und Gut aufs Pferd und reiten wir entlang des Tuul Flußes. Tuul Fluß fließt auch durch Ulaanbaatar. Unterwegs haben wir Picknick-Mittagessen. Wir reiten weiter hoch entlang des Flusses. (Zelt Übernachtung)",
      "4.Tag: Heute reiten wir durch die schöne Naturschutgebiet Gorhi-Terelj. Picknick-Mittagessen. Übernachtungsplatz ist am Ufer von Fluß Tuul, welche Länge beträgt 819 km. (Zelt Übernachtung)   ",
      "5.Tag: Weiterreitend kommen wir ein in unberührter und wunderschöner Ort namens HERHLURIN SARDAG im Naturschutzgebiet Khan Hent an. (Zelt Übernachtung)",
      "6.Tag: Freie Tag am Ufer des See Hagiin Har. Man kann wandern, angeln oder eben nur relaxen. Abends werden wir Feuerfest veranstalten. (Zelt Übernachtung)  ",
      "7.Tag: Reiten wir zurück und kommen in eine Stelle Yudgiin Pass. (Zelt Übernachtung)  ",
      "8.Tag: Heute reitend campieren wir an Zagaan hutul. (Zelt Übernachtung)  ",
      "9.Tag: Am letzten Tag reiten wir zurück zu Pferdebesitzerfamilie. Pferde Übergabe. Besuch und Bekanntschaft mit der Mongolischen Bräuchen und Kultur. Zu Abschiedsabend gibt es ganz besonders angefertigtes Essen. (Zelt Übernachtung)  ",
      "10.Tag: Fahrt nach Ulaanbaatar. Unterkommen im Hotel. Einkaufsmöglichkeit von mongolischen berühmten Cashmer. Besuch in Nationales Folklorekonzert und Abendessen. (Hotel Übernachtung)  ",
      "11.Tag: Abfahrt zu Flughafen. Abflug",

      "Im Preis enthalten:",
      "Unterkunft: 2 Nächte im 3-4 sterniges Hotel mit 2 Betten ",
      "8 Nächte im Zelt ",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden",
      "",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip6_2, trip6_3, trip6_4],
  },
  {
    id: "trip7",
    name: "Gobi Reise",
    mainImg: trip7_main,
    desc: "Die Gobi ist die größte Wüstenregion Asiens und die fünftgrößte der Welt. Eine Reihe von städtischen Gebieten entlang der Seidenstraße befinden sich in Gobi. ",
    desc2:
      "Es wird gesagt, dass Gobi aufgrund geringer Niederschläge entstanden ist, weil die majestätische Himalaya-Bergkette die Regenwolken blockiert, die in diese Region kommen. Die Gobi ist in Bezug auf Natur, Klima und Topografie äußerst vielfältig und weist eine reiche seltene Flora und Fauna auf. Insbesondere ist es berühmt für den Fund seltener Fossilien antiker Dinosaurier in der Region Umnogov.",
    nights: "7 Nächte",
    days: "8 Tage",
    meeting: "29.05.2023, 17.07.2023, 21.08.2023, 18.09.2023",
    group: "2-12",
    price: "1600$ - 900$",
    hotel: "Zelte, Ger camp, Hotel",
    transport: "4x4 Mini van, Mini van, Mongolische Pferde, Kamel",
    paragraph: [
      "1 Tag: Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen -Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2 Tag: Am Morgen fahren wir in Richtung Süden. In Dundgovi aimak werden wir die Nacht verbringen in einem Felsenkomplex mit einer merkwürdigen natürlichen Formation namens Baga Gazriin Chuluu, einem Granitberg in der Provinz Dundgov. (Übernachtung im Zelt) ",
      "3 Tag: Nach dem Frühstück passieren wir Dalanzadgad, das Zentrum der Provinz Umnogov und besuchen die Yol Am, die eine der einzigartigen Aussichten auf den Berg Gobi Gurvansaikhan am Ende des Altai-Gebirges bietet. Vom Berg aus können Sie Yol, den größten Raubvogel der Mongolei und andere Vogelarten beobachten. (Übernachtung im Ger camp)",
      "4 Tag: Das nächste Ziel unserer Reise sind die wunderschönen Hongor Sanddünen. Der Sandberg, der von der Basis bis zur Spitze 10 bis 195 Meter hoch ist und sich 185 km von West nach Ost erstreckt, wird Hongor-Flußsand genannt. Der Sandberg befindet sich im Gebiet Sevrey Sum und grenzt an den Berg Sevrey. Zwei Flüsse, Serun Bulag und Hongor Fluß, fließen entlang seiner Ränder, und das Gras des Flusses ist eine wunderschöne Oase, wo es auf die Sandberge trifft. Somit bilden sie atemberaubendes Bild. (Übernachtung im Zelt)",
      "5 Tag: An diesem Tag besuchen wir einen Ort namens Bayanzag. Der Paläontologe Roy Chapman Andrews, der in den 1920er Jahren die vom American Museum of Natural History organisierte zentralasiatische Expedition leitete, nannte die Rote Küste „Flaming Cliffs“ wegen der leuchtend orangen Farbe der Klippen, die man bei Sonnenuntergang sehen kann. Ulaan-Ereg ist berühmt für die Entdeckung des ersten Dinosaurier-Eies der Welt und ist ein historisches und kulturelles unbewegliches Denkmal unter staatlichem Schutz. (Übernachtung im Ger camp)",
      "6 Tag: Am nächsten Tag verbringen wir die Nacht in Tsagaan Suvraga, einem ummauerten Tempel. Es wurde enstanden aus uralten Meeresbodenschlamm, die durch den Wind und Wasser lies es aus der Ferne wie eine Stupa aussehen. (Übernachtung im Zelt)",
      "7 Tag: Fahrt nach UB. Einkaufsmöglichkeit in nationalen Brands wie cashmer. Besichtigung des Nationales Folklor und danach Abendessen. (Hotel Übernachtung)    ",
      "8 Tag: Abfahrt zu Flughafen. Abflug",
      "Im Preis enthalten:",
      "2 Nächte im 3-4 sterniges Hotel mit 2 Betten. Wenn man alleine in Zimmer unterkommen wollen, zahlen Sie drauf. ",
      "3 Nächte im Zelt ",
      "2 Nacht in Ger camp",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden    ",
      "",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip7_2, trip7_3, trip7_4],
  },
  {
    id: "trip8",
    name: "Rundreise durch Hangai Gebiet Huvsgul aimag, Schamane, Rentierzüchter",
    mainImg: trip8_Main,
    desc: "Diese Reise ist ein Ausritt durch das besondere Schutzgebiet des Khan Khenti-Gebirges entlang des Kamms des Khenti-Gebirges. Um den Ort zu erreichen, reisen Sie zu Pferd in die wilde Wildnis, erleben die Schönheit der Natur näher und passieren hohe Berge, Flüsse und Wälder.",
    desc2:
      "Historiker glauben, dass die Tsaatans aus Tuva eingewandert sind und sich in der Khuvsgul-Taiga niedergelassen haben. Tsaatangs sind eine nationale Minderheit mit eigener Sprache, Bräuchen, Religion und einzigartiger Lebensweise. Sie sprechen Uigurisch. In der Taiga sprechen sie untereinander Uigurisch. Und glauben an Schamanismus. Die Hauptbeschäftigung besteht darin, die Rentiere zu züchten und vom Jagd leben. ",
    nights: "18 Nächte",
    days: "19 Tage",
    meeting: "16.07.2023, 30.08.2023",
    group: "2-8",
    price: "3500$ - 2000$",
    hotel: "Zelte, Tee-Pee, Ger camp, Hotel",
    transport: "4x4 Mini van, Mini van, Mongolische Pferde, Kamel",
    paragraph: [
      "1.Tag: Die Reisende werden vom Flughafen abgeholt und im Hotel untergebracht. Zuerst erholen Sie sich und danach werden wir mit der Stadt kennenlernen. Als erstes werden wir Mittagessen. Danach werden wir in Wechselstelle Geldwechseln für die Kleinigkeiten. Später wir werden Gandantegchinlen -Kloster, das Kaufhaus, den Sukhbaatar-Platz und das Chingiskhaans Museum anschauen. Am Abend haben wir  Abendessen. (Hotel Übernachtung)",
      "2.Tag: Nach der Frühstück fängt unsere Reise an. Wir verlassen die Hauptstadt in west - südwestlicher Richtung und betreten Elsen Tasarhai. Es ist eine Provinz in Khangai und trifft auf einen Sandstreifen, der die Mongolei durchquert. Man kann den mongolischen Zweihöckige Kamele reiten. Genießen Sie die einzigartige Aussicht auf die Sanddünen und die einzigartige Flora und Fauna der Wüstenregion. (Übernachtung im mongolischen Ger, Yurte)",
      "3.Tag: Fahrt weiter nach Süd-West, Uvurhangai aimag. Wir werden die Ruinen der antiken Hauptstadt Khar- Horin, welches im Jahre 1220  durch Chingiskhaan gegründet wurde, besuchen. Da befindet sich der vom ersten Bogd Zanabazar gegründete alte Kloster Tuvkhun. Ein Spaziergang durch die üppigen Wälder und Lärchenwälder des Gebiets des Klosters, das sich auf der Gletscher-Bergwiese befindet. (Zelt Übernachtung)",
      "4.Tag: Fahrt nach Westen und campieren wir am Ufer von Tamir Flusses, Arkhangai aimag. (Zelt Übernachtung)",
      "5.Tag: Weiterfahrt nach Westen. Wanderung in Naturschutzpark zu erlöschener Vulkankrater Horgo. Unterkunft bei See Terhiin Zagaan. (Übernachtung im Gercamp)",
      "6.Tag: Fahrt nach Norden in Richtung See Huvsgul. Campieren wir nicht weit von Shine Ider. (Zelt Übernachtung)",
      "7.Tag: Weiterfahrt nach Norden, Huvsgul aimag. Sie verbringen die Nacht am Ufer des Khuvsgul-Sees. Der Khuvsgol-See ist der größte und tiefste See der Mongolei und gehört zu der größten Süßwassersee nicht nur der Mongolei, sondern auch der Welt. Der Khuvsgul-See gilt als einer der siebzehn alten Seen auf der Welt. (Übernachtung im Gercamp)",
      "8.Tag: Freie Tag. Man kann wandern. An diesem Tag können wir auch nur für kurze Zeit von innen sehen, wie nomadische mongolische Familien leben. Wir erklären Ihnen den 4-Jahreszeiten-Lebensart einer mongolischen Nomadenfamilie, die Rollen und Verantwortlichkeiten der Familienmitglieder. (Übernachtung im Gercamp)",
      "9.Tag: An diesem Tag werden wir durch die blaue Senke von Darkhad in der Provinz Khuvsgul fahren und kommen in Tsagaan Nuur Sum an. Im nordwestlichen Teil der Provinz Khuvsgul gibt es ein wunderschönes Naturgebiet, das als Darkhad Blue Senke bekannt ist. Dieses Gebiet ist eine große Wasserscheide mit 248 kleinen und großen Bächen, 377 Seen und Teichen und 24 Quellen. Außerdem hat dieses Gebiet eine einzigartige natürliche Formation mit scharfen, spitzen, dreieckigen Gipfeln und hohen felsigen Bergen, so dass es sowohl von ausländischen als auch von einheimischen Touristen besucht wird. (Übernachtung im Haus) ",
      "10.Tag: Heute lassen wir unsere Eisenpferd da und steigen aufs echtes Pferd um. (Zelt Übernachtung)",
      "11.Tag: Wir verbringen die Nacht in der wilden Taiga. Am Morgen wir Frühstücken und machen auf den Weg. Tsaatans leben weit entfernt von den Siedlungen und folgen der Nahrung ihrer Rentiere. An diesem Tag reitend kommen wir an dessen Wohnort und übernachten im Lager (Übernachtung in Urz-Tipis, Behausung der Rentierzüchter aus Rentierfell)",
      "12.Tag: Freie Tag. An diesem Tag lernen wir das Leben und die Lebensgrundlagen der Familie Tzaatan kennen. Die in der Khuvsgol-Taiga, dem abgelegenen nördlichen Teil der Mongolei, lebenden Tzaatans sind die letzten Rentierzüchter-Stämme auf der Erde. Nur 44 Familien haben ihre traditionelle Lebensweise bewahrt. Sie kochen den Tee aus RentierMilch und sie verwenden als Reittier im Alltag. (Übernachtung in Urz - Tipis)",
      "13.Tag: Reiten wir zurück zu Tsagaan Nuur Sum. Unterwegs schlagen wir unsere Zelte auf. (Zelt Übernachtung)",
      "14.Tag: Nachdem wir in Tsagaan Nuur Souman angekommen sind, machen wir eine Pause und gehen zum örtlichen Schamanen, wo wir über unsere körperlichen und seelischen Probleme fragen können. Es gibt keinen festen Tarif. Man entlohnt ihm wie viel Geld Sie geben möchten. (Übernachtung im Haus)",
      "15.Tag: Fahrt nach Murun. (Hotel Übernachtung)  ",
      "16.Tag: Fahrt Süd-Ost. Wir verlassen die Provinz Khuvsgul und verbringen die Nacht in der Provinz Bulgan. Unterkunft in der Nähe von Bureghangai. (Zelt Übernachtung)",
      "17.Tag: Fahrt in Richtung Süden, Tuv aimag. Heute besuchen wir den berühmten Hustain Mountain National Park. Seit das Gebiet 1993 unter besonderen Schutz gestellt wurde, um die in der Natur ausgestorbenen Wildpferde (Przewalski-Pferde) wieder anzusiedeln, hat die Zahl der Pferde mehr als 390 erreicht. Hirsche, Seidenäffchen, Antilopen und 213 Vogelarten wurden eingeführt und ihre Zahl nimmt stetig zu. Machen Sie einen Spaziergang durch den Nationalpark und sehen Sie seltene Wildtiere wie das auf der Roten Liste stehende wilde Urpferde Tahi und andere Tiere. (Zelt Übernachtung)",
      "18.Tag: Fahrt nach Ulaanbaatar. Nach Mittagessen werden wir shopping bummel durch mongolische Brands wie cashmer usw. Danach nationale Folklore. Abschieds Abendessen. (Hotel Übernachtung)  ",
      "19.Tag: Abfahrt zu Flughafen. Abflug",
      "Im Preis enthalten:",
      "2 Nächte im 3-4 sternigen Hotel, im Zimmer sind zu 2 Personen. Wenn man alleine in Zimmer            unterkommen wollen	, zahlen Sie drauf. ",
      "4 Nächte im Mongolischen Ger ",
      "7 Nächte im Zelt",
      "2 Nächte im Urz - Tipis",
      "Führungs- und Dolmetscherservice",
      "Vollpension Mahlzeiten ",
      "Getanktes Auto mit dem Fahrer",
      "Liebevolle zahme Pferde mit russischen Sattel  ",
      "Freundliche Pferdebegleiter",
      "Eintrittsgelder für Schutzgebiete und Nationalparks",
      "Museen und kulturelle Darbietungen",
      "Campingausrüstung",
      "",
      "Im Preis nicht enthalten:",
      "Internationaler Flugpreis",
      "Übergepäckgebühren",
      "Reiseversicherung ",
      "Einzelzimmerzuschlag",
      "Verschiedene sonder Getränke",
      "Persönliche Ausrüstung",
      "Die zusätzlichen Kosten für die Fotografie in Museen usw",
      "Tipp für einen Reiseleiter, Fahrer usw. ",
      "Alle zusätzlichen Kosten, die oben nicht erwähnt wurden",
      "",
      "Wenn Sie alleine oder in eine Gruppe reisen wollen, können wir die Reise nach Ihren/Euren Wunsch gestaltten. Die Preise können sich je nach Anzahl der Personen ändern.",
      "Mit vorherige Absprache kann man die Reise verlängern oder verkürzen.",
    ],
    images: [trip8_2, trip8_3, trip8_4, trip8_5, trip8_6, trip8_7, trip8_8],
  },
  {
    id: "trip9",
    name: "Lebensstil, die Bräuche und die Religion der mongolischen Nomaden",
    mainImg: trip9_Main,
    desc: " 1-tägige Reise, bei der Sie den traditionellen Lebensstil, die Bräuche und die Religion der mongolischen Nomaden verstehen und erleben können.",
    desc2:
      "Vormittags: Durch die Teilnahme am Programm „Mongolischer Nomade“ können Sie mongolische nomadische Tierzuchtkultur, Lebensstil, fünfarten von Tiere, Kleidung, traditionelle Milchprodukte und Speisen an einem Ort erleben. Die Veranstalltung wird beinhalten: ",
    days: "1 Tage",
    meeting: "11.06.2023, 24.06.2023, 02.07.2023, 29.07.2023, 06.08.2023",
    group: "2-8",
    price: "250$ - 150$",
    // hotel: 'Zelte, Hotel',
    transport: "Mini van, Mongolische Pferde",
    paragraph: [
      "• Begrüßung der Gäste im mongolischen Stil ",
      "• Besuch einer mongolischen Nomadenfamilie ",
      "• Nomadenkultur und Haushaltsstil einzuführen ",
      "• Die Gäste werden verwöhnt mit traditionellen Speisen (Tee, Milchprodukte, Airag -fermentierte Milch, Milchschnaps usw.) ",
      "• Pferdekopfgeige und mongolischen Volksliedern ",
      "• Lassen Sie die Gäste an einem kleinen Fest teilnehmen, indem sie Finger Erratenspiel, fingern, duet Gesang",
      "• Vorstellung, wie man das fünfarten von Tieren hütet ",
      "• Melken von Schafen und Ziegen unter Beteiligung der Gäste ",
      "• Durchführung und Verarbeitung von getrockneten Quark- und Destillation von Milchschnaps zur Verkostung durch die Gäste ",
      "• Bogenschießen ",
      "• Nationale Spiele mit Gästen spielen (Knöchel spielen, Knöchel schießen) ",
      "• Mit den Gästen zusammen die Schafswolle verarbeiten ",
      "• Lederriemen verarbeiten",
      "• Praktische demonstrieren, wie man sich mit typischen Fahrzeugen wie Ochsenkarren, Yakpack, Kamelkarren, Pferdekarren Umzug gemacht. Nachdem Sie sich diese schöne Veranstalltung angesehen haben, essen Sie in diesem Camp zu Mittag und gehen Sie zur nächsten Attraktion. ",
      "Nachmittag: Am Nachmittag fahren wir zum Kloster Aglag. Der Aglag-Tempel befindet sich im „Dalii Am“-Gebiet von Nart, Bornuur Sum, Tuv aimag, und ist ein Klostermuseum, das auf den ungewöhnlichen Formationen des Gard-Berges basiert. Neben traditionellen Malereien und Dekorativenmasken bietet das Gebiet mit interessante Lösungen. Da kann man verschieden Arten von Fischen und seltsame Kreationen ansehen. ",
      "Neben der kuriosen Sammlung von Einhornschädel, Vierhorn-Widder, Sechshorn-Antilope, Einhorn-Steinbock, Sechszahn-Wildschwein, Hornhase, Blütenhorn-Antilope, Fünfkopffisch usw. können Sie sich all das anschauen. Lama Purevbat hat mit seinen Lehrlingen zusammen Gard-Gebirgsformationen, große Felsen und interessante Bäume in der Natur bearbeitet und viele Schnitzereien angefertigt, wie Hangard Vogel, Tiger usw. Beim Besuch der Agla-Moschee ist es nicht notwendig, Räucherstäbchen, Alkohol, Milch und Reis mitzubringen. Dies liegt daran, dass sie die Entstehung von Müll im Kloster Umfeld und die Entstehung eines schlechten Geruchs verhindern. Das Wichtigste ist, frische Luft zu atmen, den Geist zu entspannen und gute Energie und Energie aus der Umgebung von Tempeln, Göttern und zehn vergrabenen Felsen zu schöpfen. Nach dem Besuch der Kloster und des Museums bringen wir Sie zurück zu Ihrem Hotel, wo unsere eintägige Tour endet.",
    ],
    images: [trip9_2, trip9_4, trip9_5, trip9_6, trip9_7],
  },
  {
    id: "trip10",
    name: "Lebensweise der mongolischen Nomaden",
    mainImg: trip10_Main,
    desc: "Auf dieser 1-tägigen Reise zeigen wir Ihnen die traditionelle Lebensart und Lebensweise der mongolischen Nomaden. Nicht jeder kann zeitlich den Mongolischen Nationalfeier Naadam zu erleben, daher haben wir für Sie extra ein kleines Naadamfest organisiert. ",
    desc2:
      "Der Vorteil von Besreg Naadam ist, dass es nicht möglich ist, alle Wettbewerbe und Aufführungen zu sehen, die hier und da während des Nationalfestivals stattfinden. Aber bei Besreg Naadam können Sie alles in einem Ort erleben.",
    // nights: '10 Nächte',
    days: "1 Tage",
    meeting: "27.06.2023, 04.07.2023, 25.07.2023, 03.08.2023, 14.08.2023, 28.08.2023, 06.09.2023 ",
    group: "2-8",
    price: "300$ - 200$",
    // hotel: 'Zelte, Hotel',
    transport: "Mini van, Mongolische Pferde",
    paragraph: [
      "9.00 мин: Morgen holen wir Sie vom Hotel ab und fahren zur Veranstalltungort hin. ",
      "10.00 мин: Sie können Sie mongolische nomadische Tierzuchtkultur, Lebensstil, fünfarten von Tiere, Kleidung, traditionelle Milchprodukte und Speisen an einem Ort erleben. Die Veranstalltung wird beinhalten: ",
      "• Begrüßung der Gäste im mongolischen Stil ",
      "• Besuch einer mongolischen Nomadenfamilie ",
      "• Einfürung zur Nomadenkultur und Haushaltsstil ",
      "• Die Gäste werden verwöhnt mit traditionellen Speisen (Tee, Milchprodukte, Airag -fermentierte Milch, Milchschnaps usw.) ",
      "• Pferdekopfgeige und mongolischen Volksliedern ",
      "• Lassen Sie die Gäste an einem kleinen Fest teilnehmen, indem sie Finger Erratenspiel, fingern, duet Gesang",
      "• Vorstellung, wie man das fünfarten von Tieren hütet ",
      "• Melken von Schafen und Ziegen unter Beteiligung der Gäste ",
      "• Durchführung und Verarbeitung von getrockneten Quark- und Destillation von Milchschnaps zur Verkostung durch die Gäste ",
      "• Bogenschießen ",
      "• Nationale Spiele mit Gästen spielen (Knöchel spielen, Knöchel schießen) ",
      "• Mit den Gästen zusammen die Schafswolle verarbeiten ",
      "• Lederriemen verarbeiten",
      "• Praktische demonstrieren, wie man sich mit typischen Fahrzeugen wie Ochsenkarren, Yakpack, Kamelkarren, Pferdekarren Umzug gemacht. Nachdem Sie sich diese schöne Veranstalltung angesehen haben, essen Sie in diesem Camp zu Mittag und gehen Sie zur nächsten Attraktion. ",
      "12.30: Mittagessen",
      "14.00: Festivalprogramm:",
      "Viele Zelte, das die mongolischen Naadamfest darstellt, viele Besucher in farbenfrohen nationalen Tracht wie Blumen, kraftvolle Ringer, schnelle Pferde, die kaum auf ihren Geschirren stehen können, Kinder, die mit lauten Liedern reiten, scharfe Bogenschützen, der wunderbare Klang Urtiin duu-langer Lieder, der überwältigende Mongole Tanz und der Duft von vergorenen Stutenmilch-Airag, heißen Sie willkommen. Programm:",
      "•	Eröffnung mit Urtiin duu-langer Lied, Pferdekopfgeige  ",
      "•	Tradizionalles Tanez ",
      "•	Erste Runde von stärksten 16 Ringkämpfer",
      "•	Mongolische tradizionalle Musik, Gesang, Kehlkopfgesang - Hoomii",
      "•	Kinderjockeys galoppieren über das Festivalgelände, während sich die Pferde zur Startlinie bewegen    ",
      "•	Zweite Runde von Ringkampf",
      "•	Tradizionalles Tanez ",
      "•	Demonstrationsbogenschießen von Bogenschützer auf dem Bogenschießplatz   ",
      "•	Festivalbesucher testen ihre Fähigkeiten beim Bogenschießen ",
      "•	Dritte Runde von Ringkampf",
      "•	Festivalbesucher gehen zur Ziellinie und die Pferde kommen ins Ziel  ",
      "•	Tradizionalles Tanez ",
      "•	Die besten Pferde und Reiter werden prämiert  ",
      "•	 Die Finalrunde von Ringkampf",
      "•	Die Sieger von Ringkampf werden prämiert    ",
      "•	16.30: Rückfahrt nach Ulaanbaatar. Unsere eintägige Reise in das Leben und die Feste unseres nomadischen mongolischen Volkes endet, in dem Sie Ihren Hotel erreicht haben ",
    ],
    images: [trip10_2, trip10_3, trip10_4, trip10_5],
  },
];
